// Copyright (C) 1991-2009 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II Version 9.0 (Build Build 235 06/17/2009)
// Created on Thu Dec 05 15:05:40 2019

square3 square3_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.row(row_sig) ,	// input [9:0] row_sig
	.column(column_sig) ,	// input [9:0] column_sig
	.upDown(upDown_sig) ,	// input  upDown_sig
	.leftRight(leftRight_sig) ,	// input  leftRight_sig
	.enableUpDown(enableUpDown_sig) ,	// input  enableUpDown_sig
	.enableLeftRight(enableLeftRight_sig) ,	// input  enableLeftRight_sig
	.draw(draw_sig) ,	// output  draw_sig
	.draw2(draw2_sig) 	// output  draw2_sig
);

